# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-12-14T17:29:49+00:00

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum, StrEnum
from typing import List, Optional

import dacite

config = dacite.Config(cast=[int, str], type_hooks={
    datetime: datetime.fromisoformat
    })

@dataclass
class E621_Post:
    id: int | str
    created_at: datetime
    updated_at: datetime
    # created_at: str
    # updated_at: str
    file: File
    preview: Preview
    sample: Sample
    score: Score
    tags: Tags
    locked_tags: List[str]
    change_seq: float
    flags: Flags
    rating: Ratings
    fav_count: int
    sources: List[str]
    pools: List[int]
    relationships: Relationships
    approver_id: int | str | None
    uploader_id: int | str | None
    description: str | str | None
    comment_count: int | str | None
    is_favorited: bool
    has_notes: bool
    duration: float | None
    uploader_name: str

    @staticmethod
    def parse_e621_post(post_dict) -> E621_Post:
        return dacite.from_dict(E621_Post, post_dict, config=config)


class Ratings(StrEnum):
    s = "s"
    q = "q"
    e = "e"


@dataclass
class File:
    width: int | None
    height: int | None
    ext: str | None
    size: int | None
    md5: str | None
    url: str | None


@dataclass
class Preview:
    width: int | None
    height: int | None
    url: str | None


@dataclass
class Score:
    up: int
    down: int
    total: int


@dataclass
class Tags:
    general: List[str]
    artist: List[str]
    copyright: List[str]
    character: List[str]
    species: List[str]
    invalid: List[str]
    meta: List[str]
    lore: List[str]
    contributor: List[str]


@dataclass
class Flags:
    pending: bool
    flagged: bool
    note_locked: bool
    status_locked: bool
    rating_locked: bool
    deleted: bool


@dataclass
class Relationships:
    parent_id: int | str | None
    has_children: bool
    has_active_children: bool
    children: List[int]


class Type(Enum):
    flag = "flag"
    deletion = "deletion"


@dataclass
class PostSampleAlternate:
    fps: float
    codec: str
    size: int
    width: int
    height: int
    url: str


@dataclass
class Variants:
    webm: Optional[PostSampleAlternate] = None
    mp4: Optional[PostSampleAlternate] = None


@dataclass
class Samples:
    field_480p: Optional[PostSampleAlternate] = None
    field_720p: Optional[PostSampleAlternate] = None


@dataclass
class Alternates:
    has: Optional[bool] = None
    original: Optional[PostSampleAlternate] = None
    variants: Optional[Variants] = None
    samples: Optional[Samples] = None


@dataclass
class Sample:
    has: bool
    height: int
    width: int
    url: str | None
    alternates: Alternates
