[app]
limit = 30000
log_level = "INFO"
id_length = 8
cache_dir = ".metadata_cache"
cache_ttl = 300
db_dir = ".db"
db_file_name = "tagapp.db"
db_blob_name = "blob.db"
thumbnail_width = 640
thumbnail_height = 480

[r34]
enabled = false
artists = []
black_list = []
api_key = ""

[e621]
enabled = false
artists = []
black_list = []
api_key = ""
username = ""

[danbooru]
enabled = false
artists = []
black_list = []
api_key = ""
username = ""

[eagle]
enabled = false
endpoint = "http://localhost:41595/api"
library = ""
artist_folder = ""

[local]
enabled = true
artist_dir = "media"
