name: UV sync and create executable

on: [push, pull_request]
jobs:
  build:
    name: Build distribution 📦
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
    - name: Set up Python
      run: uv python install
    - name: Sync Dependencies
      run: uv sync --locked --all-extras --dev
    - name: Install package
      run: uv pip install .
    - name: Build executable
      run: uv run pyinstaller --collect-all ttkbootstrap --name ArtRefSync  main.py
    - name: Store the distribution packages
      uses: actions/upload-artifact@v6
      with:
        name: python-package-distributions
        path: dist/



