name: Package exe and publish to store

on: [push, pull_request]

jobs:
  build:
    name: Build distribution 📦
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"
    - name: Update pip
      run: python3 -m pip install --upgrade pip
    - name: Install pypa/build
      run: python3 -m pip install pyinstaller --user
    - name: Install dependencies before testing
      run: python3 -m pip install . --user
    - name: Run pyinstaller
      # run: pyinstaller main.py --collect-all ttkbootstrap --name ArtRefSync
      run: pyinstaller main.spec
    - name: Store the distribution packages
      uses: actions/upload-artifact@v6
      with:
        name: python-package-distributions
        path: dist/